Provide simple setup script.

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,24 +1,34 @@
 #!/bin/sh -e
 
-# Spell-check the commit message.
+# Validate the commit message.
+
+MAX_LENGTH=60
+fatal() { printf '\033[31mERROR: %s\033[0m\n' "$*" ; exit 1 ; }
 
 
-# Wrap calls to run checks in container.
-sif="$HOME/l/sif/pytorch_2.6.0-cuda12.6-cudnn9-runtime.sif"
-env() { app_exec.sh "$sif" "$@" ; }
-
-
-echo "Checking message"
-
-
-# Make sure it fits in one line on GitHub.
-max=60
-len=$(wc -m "$1" | awk '{print $1}')
-if [ "$len" -gt "$max" ]; then
-    echo "Message length is $len but should not exceed 60 characters"
-    exit 1
+# Length. GitHub summaries fit 60 characters.
+echo "Checking message length"
+len=$(awk '{print length($0); exit} ' "$1")
+if [ -z "$len" ]; then
+    fatal "message is empty"
+elif [ "$len" -gt "$MAX_LENGTH" ]; then
+    fatal "message length is $len but should not exceed $MAX_LENGTH"
 fi
 
 
-# Run the spell checker.
-env typos "$1"
+echo "Checking space characters"
+if awk '/(^ )|(  )|( [,!?])/ {exit 0} {exit 1}' "$1"; then
+    fatal "misplaced space characters in message"
+fi
+
+
+# Sentence.
+echo "Checking sentential validity"
+if awk '/^[A-Z].*[.?!]$/ {exit 1} {exit 0}' "$1"; then
+    fatal "message does not start with [A-Z] and end in [.?!]"
+fi
+
+
+# Spelling.
+echo "Checking message spelling"
+typos "$1"
